server:
  port: 8080
spring:
  application:
    name: USERS-SERVICE
  config:
    import: configserver:http://localhost:9000
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/usersdb
    username: postgres
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update

#eureka:
#  instances:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}