apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
spec:
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
      - name: user-service-app
        image: IMAGE_URL/user-service
        ports:
          - containerPort: 8080
        env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: CONFIG_SERVER_URL
                name: config-cm
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: postgresql-cm

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  selector:
    app: user-service-app
  ports:
  - port: 80
    targetPort: 8080
        
